---
title: "Analyze data using ArchR"
author: "Mingbo Cheng"
date: '`r format(Sys.Date(), "%Y-%B-%d")`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F, echo = T,cache=F)
library(ggplot2)
library(stringr)
library(magrittr)
library(WriteXLS)
library(tidyr)
library(dplyr)
library(plotly)
library(cluster)
library(cowplot)
library(gridExtra)
library(viridis)
library(GenomicRanges)
library(GenomeInfoDb)
library(data.table)
library(ArchR)
library(glue)
```

```{r set_parameters, echo=FALSE}
## set parameters
set.seed(42)
addArchRThreads(threads = 100)
addArchRGenome("mm10")
```

## Reading barcodes
```{r}
message("Reading in integrated data...")
ref_atac_file <- "../../../Seurat3/IntegrationWithscOpen/obj.integrated_annotated_day3_myo.Rds"
atac <- readRDS(ref_atac_file)
meta_data <- atac@meta.data
print(colnames(meta_data))

fib_meta_data <- subset(meta_data, celltype %in% c("Fibroblasts",
                                                   "Myofibroblasts",
                                                   "Pericytes/vSMC"
                                                   ))


```


## Creating Arrow Files
```{r}
#inputFiles <- c("Heart" = "../../Aggregation/Heart/outs/fragments.tsv.gz")
inputFiles = "../save/fib/fragments.tsv.bgz"
names(inputFiles) <- "Fibroblasts"


minTSS <- 1
minFrags <- 100

ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = names(inputFiles),
  outputNames = names(inputFiles),
  validBarcodes = rownames(fib_meta_data),
  minTSS = minTSS, 
  minFrags = minFrags, 
  maxFrags = 1e+07,
  QCDir = "QualityControl",
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)

ArrowFiles
```


## Session information
```{r}
sessionInfo()
```
